// Post-render color grade pass — apply a 3D LUT (.cube) to a rendered MP4.
//
// "What makes browser-rendered footage look 'cinematic'": a final unified color
// grade across the whole timeline. ffmpeg's `lut3d` filter takes a .cube file
// (the universal LUT format used by Resolve, Premiere, Final Cut) and applies
// it to every frame.
//
// Usage:
//   node scripts/post-grade.mjs renders/foo.mp4
//   node scripts/post-grade.mjs renders/foo.mp4 --lut=teal-orange
//   node scripts/post-grade.mjs renders/foo.mp4 --lut=path/to/custom.cube
//   node scripts/post-grade.mjs renders/foo.mp4 --lut=teal-orange --strength=0.7
//
// Built-in LUTs (synthesized procedurally — no external files needed):
//   teal-orange  — pushes shadows cyan, highlights warm (Hollywood default)
//   noir         — high-contrast desaturated B&W with faint blue cast
//   warm         — golden-hour lift + saturation bump
//   cool         — cyan/blue cast for night/tech feel
//   pop          — punchy contrast + saturation, no hue shift
//   vintage      — faded blacks, lifted shadows, cream highlights
//
// Output: renders/<name>-graded.mp4 alongside the source.
// The original is left untouched. Re-run with different LUTs to A/B compare.

import path from "path";
import fs from "fs";
import { spawn } from "child_process";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");
const lutCacheDir = path.join(projectRoot, "assets", ".cache", "luts");

// --- Built-in LUT generators ---------------------------------------------
// .cube format spec: https://wwwimages2.adobe.com/content/dam/acom/en/products/speedgrade/cc/pdfs/cube-lut-specification-1.0.pdf
// We bake 17×17×17 LUTs (4913 entries) — small enough to ship, accurate
// enough that the eye can't tell from 33×33×33.

const SIZE = 17;

function buildCube(name, transform) {
  const lines = [
    `# Generated by aivideomaker post-grade.mjs — preset "${name}"`,
    `LUT_3D_SIZE ${SIZE}`,
    "DOMAIN_MIN 0.0 0.0 0.0",
    "DOMAIN_MAX 1.0 1.0 1.0",
    "",
  ];
  for (let b = 0; b < SIZE; b++) {
    for (let g = 0; g < SIZE; g++) {
      for (let r = 0; r < SIZE; r++) {
        const inR = r / (SIZE - 1);
        const inG = g / (SIZE - 1);
        const inB = b / (SIZE - 1);
        const [oR, oG, oB] = transform(inR, inG, inB);
        lines.push(
          `${oR.toFixed(6)} ${oG.toFixed(6)} ${oB.toFixed(6)}`
        );
      }
    }
  }
  return lines.join("\n");
}

const clamp = (v, lo = 0, hi = 1) => Math.max(lo, Math.min(hi, v));
const lerp  = (a, b, t) => a + (b - a) * t;
const mix   = (color, target, t) => color.map((c, i) => lerp(c, target[i], t));
const lum   = (r, g, b) => 0.2126 * r + 0.7152 * g + 0.0722 * b;

const LUT_PRESETS = {
  // Teal in shadows, orange in highlights — the most-used cinematic grade.
  "teal-orange": (r, g, b) => {
    const l = lum(r, g, b);
    const shadowMix = 1 - clamp(l * 1.6, 0, 1);
    const highMix   = clamp((l - 0.5) * 1.8, 0, 1);
    let [oR, oG, oB] = [r, g, b];
    [oR, oG, oB] = mix([oR, oG, oB], [0.05, 0.32, 0.42], shadowMix * 0.35);
    [oR, oG, oB] = mix([oR, oG, oB], [1.00, 0.62, 0.18], highMix   * 0.30);
    // Slight contrast lift
    [oR, oG, oB] = [oR, oG, oB].map(c => clamp(0.5 + (c - 0.5) * 1.10));
    return [oR, oG, oB];
  },

  // Desaturated near-monochrome with a faint blue lift in shadows.
  noir: (r, g, b) => {
    const l = lum(r, g, b);
    const desat = 0.92;
    let oR = lerp(l, r, 1 - desat);
    let oG = lerp(l, g, 1 - desat);
    let oB = lerp(l, b, 1 - desat);
    // Lift shadow blues
    const shadowMix = 1 - clamp(l * 1.5, 0, 1);
    [oR, oG, oB] = mix([oR, oG, oB], [0.10, 0.16, 0.30], shadowMix * 0.20);
    // High-contrast curve
    [oR, oG, oB] = [oR, oG, oB].map(c => clamp(0.5 + (c - 0.5) * 1.25));
    return [oR, oG, oB];
  },

  // Golden-hour warmth — for friendly/inviting brand work.
  warm: (r, g, b) => {
    let oR = clamp(r * 1.06 + 0.02);
    let oG = clamp(g * 1.02 + 0.01);
    let oB = clamp(b * 0.94);
    [oR, oG, oB] = [oR, oG, oB].map(c => clamp(0.5 + (c - 0.5) * 1.05));
    // Saturation +6%
    const l = lum(oR, oG, oB);
    [oR, oG, oB] = [oR, oG, oB].map((c) => clamp(l + (c - l) * 1.06));
    return [oR, oG, oB];
  },

  // Cool/tech — for SaaS, fintech, anything "modern infrastructure."
  cool: (r, g, b) => {
    let oR = clamp(r * 0.94);
    let oG = clamp(g * 1.00);
    let oB = clamp(b * 1.08 + 0.02);
    const l = lum(oR, oG, oB);
    [oR, oG, oB] = [oR, oG, oB].map((c) => clamp(l + (c - l) * 1.05));
    return [oR, oG, oB];
  },

  // Punchy contrast + sat, no hue shift. Safe default for any brand.
  pop: (r, g, b) => {
    let oR = clamp(0.5 + (r - 0.5) * 1.12);
    let oG = clamp(0.5 + (g - 0.5) * 1.12);
    let oB = clamp(0.5 + (b - 0.5) * 1.12);
    const l = lum(oR, oG, oB);
    [oR, oG, oB] = [oR, oG, oB].map((c) => clamp(l + (c - l) * 1.12));
    return [oR, oG, oB];
  },

  // Lifted shadows + cream highlights — film-stock fade.
  vintage: (r, g, b) => {
    let oR = lerp(0.06, 0.96, r);
    let oG = lerp(0.05, 0.93, g);
    let oB = lerp(0.08, 0.86, b);
    [oR, oG, oB] = mix([oR, oG, oB], [1.0, 0.92, 0.78], 0.10);
    const l = lum(oR, oG, oB);
    [oR, oG, oB] = [oR, oG, oB].map((c) => clamp(l + (c - l) * 0.90));
    return [oR, oG, oB];
  },
};

// --- Helpers --------------------------------------------------------------

function ensureLutFile(name) {
  if (!LUT_PRESETS[name]) {
    if (fs.existsSync(name)) return path.resolve(name);
    throw new Error(
      `Unknown LUT "${name}". Built-in: ${Object.keys(LUT_PRESETS).join(", ")}`
    );
  }
  fs.mkdirSync(lutCacheDir, { recursive: true });
  const out = path.join(lutCacheDir, `${name}.cube`);
  if (!fs.existsSync(out)) {
    fs.writeFileSync(out, buildCube(name, LUT_PRESETS[name]));
  }
  return out;
}

function ffmpegPath() {
  // Prefer environment, fall back to known winget install location (LEARNINGS.md §2)
  if (process.env.FFMPEG) return process.env.FFMPEG;
  return "ffmpeg";
}

function run(cmd, args, opts = {}) {
  return new Promise((resolve, reject) => {
    const p = spawn(cmd, args, { stdio: "inherit", ...opts });
    p.on("close", (code) => (code === 0 ? resolve() : reject(new Error(`${cmd} exited ${code}`))));
    p.on("error", reject);
  });
}

// --- CLI ------------------------------------------------------------------

const argv = process.argv.slice(2);
const flags = Object.fromEntries(
  argv.filter(a => a.startsWith("--")).map(a => {
    const [k, v] = a.replace(/^--/, "").split("=");
    return [k, v ?? true];
  })
);
const positional = argv.filter(a => !a.startsWith("--"));
const input = positional[0];
const lutName = flags.lut || "teal-orange";
const strength = parseFloat(flags.strength ?? "1.0");

if (!input) {
  console.error("Usage: node scripts/post-grade.mjs <input.mp4> [--lut=name] [--strength=0..1]");
  console.error(`Built-in LUTs: ${Object.keys(LUT_PRESETS).join(", ")}`);
  process.exit(2);
}

if (!fs.existsSync(input)) {
  console.error(`Input not found: ${input}`);
  process.exit(2);
}

const lutPathAbs = ensureLutFile(lutName);
const ext = path.extname(input);
const base = input.slice(0, -ext.length);
const output = `${base}-graded${ext}`;

// ffmpeg's filter parser treats `:` as an arg separator, which breaks Windows
// `C:\` absolute paths. Run ffmpeg from projectRoot and pass a relative path
// (no drive-letter colon) for the LUT. Inputs/outputs go through `-i`/output
// args, not the filter graph, so they tolerate absolute paths.
const lutPath = path.relative(projectRoot, lutPathAbs).replace(/\\/g, "/");

// Strength via blend: original at (1-s) + graded at s, applied per-frame.
// We use lavfi split + lut3d on one branch + blend.
const filter =
  strength >= 0.999
    ? `lut3d=${lutPath}`
    : `split[a][b];[b]lut3d=${lutPath}[g];[a][g]blend=all_mode=normal:all_opacity=${strength.toFixed(3)}`;

const args = [
  "-y",
  "-i", input,
  "-vf", filter,
  "-c:v", "libx264",
  "-preset", "medium",
  "-crf", "18",
  "-c:a", "copy",
  "-movflags", "+faststart",
  output,
];

console.log(`▶ grading ${path.basename(input)} with "${lutName}" @ strength=${strength}`);
console.log(`  LUT cube:  ${lutPath}`);
console.log(`  output:    ${output}`);

await run(ffmpegPath(), args, { cwd: projectRoot });
console.log(`✓ done — ${output}`);
